### ISSUE TITLE
Export Project with the plug-in

### ISSUE THREAD

**Issue by MarcelBock** [getnamo/tensorflow-ue4#37] opened 2018-10-17 15:48 UTC
Hello, 

I have used your Plug-in for my masterthesis and I want to create a windows executable of my scene, so other users without Unreal Engine can use my programm. 
Could you write a tutorial or add a section to the README and explain how this is possible? I have a lot of difficulties to create the .exe and the documentation of the Unreal Engine is not very good for this problem. 
If you could give me some feedback or advice soon, that would be very very appreciated (I have to submit my masterthesis next Tuesday). 
Thanks a lot for your help!
Best regards
Marcel #

**Comment by getnamo** [comment] 2018-10-17 22:13
Duplicate of https://github.com/getnamo/tensorflow-ue4/issues/16, but I'll take a quick look at packaging today to see how hard this problem potentially is.

**Comment by MarcelBock** [comment] 2018-10-18 07:55
Ah, sorry, I have not seen #16, will have a lookt at it, today. But thanks for your reply and that you will have a look at it as well :) Using the 0.80 for UE 4.19 by the way

**Comment by getnamo** [comment] 2018-10-20 18:45
Added support for packaging in [new release v0.9.3](https://github.com/getnamo/tensorflow-ue4/releases/tag/0.9.3). You'll need to update to UE 4.20 for everything to work out of the box.

See https://github.com/getnamo/tensorflow-ue4#packaging for instructions.

**Closed by getnamo** 2018-10-20 18:45 UTC
Labels: duplicate
